### ISSUE TITLE
MVP and other, unsorted, to-do things

### ISSUE THREAD

**Issue by kosovojs** [kosovojs/missing-tool#1]
- [ ] option to save results in DB, giving title to query
- [ ] cron? - option for automatic updates of results
- [ ] rate-limiter? 5 reqs/min?
- [ ] add possibility to choose which language wikipedia's titles to use
- [ ] option to download results - json, csv, tsv, wikitable, excel
- [ ] wrapper for easier API calls like "base_url/en/lv/category/2020 Summer Olympics/5"
- [ ] add input option for Quarry
- [ ] autocomplete for categories, templates
- [ ] passing categories/templates in URL
- [ ] handle template and category redirects
